services:
  - type: web
    name: graffiti-wall-webapp
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn webapp.main:app --host 0.0.0.0 --port 10000
    pythonVersion: "3.11.0"
